### ISSUE TITLE
Relax fastlane version

### ISSUE THREAD

**Issue by cmckni3** [HipByte/motion-provisioning#27]
Fastlane has a newer feature version `2.116.x`.
motion-provisioning locks to `~> 2.113.0`

## Proposal

Change gemspec to lock fastlane to `~> 2.113`

**Comment by amirrajan** [comment]
Any reason to not just use the latest?

**Comment by cmckni3** [comment]
Probably not.

I noticed the gemspec was updated to lock the version. Created issues with my project running a newer version.

**Comment by andrewhavens** [comment]
@amirrajan @cmckni3 It would be a good idea to be less restrictive with the version number, but since this is a gem, we still need to be a little restrictive on the version so that things don't break when Fastlane makes changes (which has happened in the past). I'm assuming we can lock based on major version number (`~> 2.116`) but we would need to run the tests to see if that still works. Chris, I'm curious, are you using Fastlane in your project? Or are you trying to bump the version number because of a bug fix in this gem?

**Comment by cmckni3** [comment]
I am using fastlane across projects. Some non-RM projects use fastlane for automation.

My biggest gripe is Fastlane complaining about the version being outdated when running with `bundle exec`.

**Comment by andrewhavens** [comment]
@cmckni3 I pushed a commit to master that loosens the version restriction to 2.x.x instead of 2.113.x. https://github.com/HipByte/motion-provisioning/commit/ceafbf1464d4f2d0c337bec207b6fb5b80c62dd4
